---

# ***

# Ensure ~/.local/bin/bash exists, which some panel launchers use rather
# than, e.g., /bin/bash. This is useful if you want to use a custom Bash.
- name: Stat ~/.local/bin/bash
  ansible.builtin.stat: path="{{ ansible_env.HOME }}/.local/bin/bash"
  register: local_bin_bash_f

- name: Symlink ~/.local/bin/bash if not exists
  ansible.builtin.file:
    src: "/bin/bash"
    dest: "{{ ansible_env.HOME }}/.local/bin/bash"
    state: link
  when: not local_bin_bash_f.stat.exists

# ***

# CPYST:
#   dconf dump /org/mate/panel/
- name: Reset Existing MATE Panel DConf, and Clear ~/.config/mate/panel2.d/default/launchers/
  ansible.builtin.shell: dconf reset -f /org/mate/panel/

- name: Kill Off MATE Panel While We Work — Restarts it with default launchers
  ansible.builtin.shell: killall -s 9 mate-panel
  ignore_errors: yes

# ***

# E.g.,:
#   /bin/rm -rf ~/.config/mate/panel2.d/default/launchers/
- name: Clear Existing MATE Panel Launcher Files
  ansible.builtin.file:
    state: absent
    path: "{{ ansible_env.HOME }}/.config/mate/panel2.d/default/launchers/"

# CPYST:
#   ll ~/.config/mate/panel2.d/default/launchers/
- name: Ensure MATE Panel Launcher Directory Exists
  ansible.builtin.file:
    state: directory
    path: "{{ ansible_env.HOME }}/.config/mate/panel2.d/default/launchers/"

- name: Deploy Most MATE Panel Launchers
  ansible.builtin.template:
    src: "{{ item }}"
    dest:
      "{{ ansible_env.HOME }}/.config/mate/panel2.d/default/launchers/{{
        item | basename | regex_replace('\\.j2$','')
      }}"
  with_fileglob:
    - ../templates/launchers/*.desktop*

- name: Deploy Dubs Vim Edit MATE Panel Launchers \#s 1-10
  ansible.builtin.template:
    src: ../templates/dubs-vim.desktop.j2
    dest: "{{ ansible_env.HOME }}/.config/mate/panel2.d/default/launchers/{{ item.id }}.desktop"
  vars:
    zoidy_matecocido_dubs_vim_name: "{{ item.name }}"
    zoidy_matecocido_dubs_vim_edit: "{{ item.edit }}"
    zoidy_matecocido_dubs_vim_icon: "{{ item.icon }}"
  loop: "{{ zoidy_matecocido_dubs_vim_launchers }}"

# ***

# CPYST:
#   ll ~/.config/zoidy_matecocido/icons/
- name: Deploy (Synchronize) MATE Panel Launcher Icons
  ansible.builtin.synchronize:
    src: "../files/launcher-icons/"
    dest: "{{ ansible_env.HOME }}/.config/zoidy_matecocido/icons/"
    delete: yes

# ***

- ansible.builtin.set_fact:
    list_sep: "', '"

- name: Format custom panel object IDs list
  ansible.builtin.set_fact:
    custom_object_ids: ", '{{ zoidy_matecocido_panel_objects | map(attribute='object_id') | join(list_sep) }}'"

# BEWARE: If you specify a position that causes overlap, mate-panel crashes.
#
# E.g., the following config
#
#   [objects/notification-area]
#   # position=1382
#   position=1409
#   ...
#
#   [objects/zoidy-workspace-switcher]
#   position=1562
#   ...
#
# crashes mate-panel.
#
# You can restart `mate-panel &`
# after fixing the error.
#
# Oddly, after you set the config, you can unlock notification-area
# and move it rightward, so that its position is the same value that
# crashed mate-panel. Oh, well.
- name: Format default panel DConf, including custom object IDs
  ansible.builtin.set_fact:
    org_mate_panel_dconf: "{{ lookup('template', 'templates/org-mate-panel.dconf.j2') }}"

# ***

- name: Generate custom panel sections
  ansible.builtin.shell: |
    echo "[objects/{{ item.object_id }}]
    toplevel-id='bottom'
    object-type='launcher'
    launcher-location={{ item.launcher_location }}
    position={{ item.position }}
    locked=true
    panel-right-stick=false
    "
  # position={{ 36 + (index > 1 and 35 or 0) + (index > 2 and (31 * (index - 2)) or 0) }}
  # 2023-04-22: Some launchers in Mint 21.1 (Firefox, mate-terminal, caja) include menu-path:
  #   menu-path='applications:/'
  # 2023-04-22: Default Mint 21.1 shows only 'panel-right-stick=true' usage.
  # - I.e., defaults false, so don't need to specify.
  register: dconf_launcher_cmds
  loop: "{{ zoidy_matecocido_panel_objects }}"
  loop_control:
    index_var: index

- name: Format custom MATE panel DConf parts
  ansible.builtin.set_fact:
    dconf_launcher_objects: "{{ dconf_launcher_cmds.results | map(attribute='stdout') | join('\n') }}"

# ***

- name: Load Custom MATE Panel DConf
  ansible.builtin.shell: dconf load /org/mate/panel/
  args:
    stdin: "{{ org_mate_panel_dconf + dconf_launcher_objects }}"

# ***

# ISOFF/2024-02-08: I often get bit by mouse scrolling: I'll be using mouse
# wheel to scroll through Vim, or Chrome, or a terminal, and I'll have the
# mouse near the bottom of the window, but I'll inadvertently drift over the
# window-list. Then, all of a sudden, there's a rapid fire cascade of other
# windows popping to the front, because I gave focus to the window-list.
# - Long story short, disable mouse scrolling.

- name: Disable window-list "Disable mouse scrolling"
  ansible.builtin.shell: dconf write /org/mate/panel/objects/window-list/prefs/scroll-enabled false

# ***

# ISOFF/KLUGE/2024-03-01: (On LM 21.3 at least) Oftentimes when you click
# the same window-list button more than once while never leaving focus,
# clicking to maximize is ignored. E.g., if I hover over the Vim window-list
# button and click, Vim is minimized, and another window comes to the front.
# But if I click again, nothing happens. However, the Vim button is still
# highlighted. And if I move the mouse off the Vim button, the highlight
# moves from Vim to the other window that was fronted. And then I can click
# Vim to maximize it. Which is annoying. So disabling this option.

# [LM 21.3] Window List Preferences > Behavior [tab] > Window Thumbnails >
# - ✗ Show thumbnails on hover
- name: Disable window-list "Show thumbnails on hover"
  ansible.builtin.shell: dconf write /org/mate/panel/objects/window-list/prefs/show-window-thumbnails false

# ***

# Remove the ⋮ three vertical dots/ellipsis that appear to the left of the window-list
# and to the left of the notification area.
# - DUNNO: Oddly, I cannot grab the dots, or do anything with them.
#   - What's their purpose? Am I missing something?
# - REFER: https://forums.linuxmint.com/viewtopic.php?t=323799

- name: Hide vertical ellipsis from window-list and from notification area
  ansible.builtin.lineinfile:
    path: "{{ ansible_env.HOME }}/.config/gtk-3.0/gtk.css"
    line: 'MatePanelAppletFrameDBus > MatePanelAppletFrameDBus { background: none; }'
    regexp: '^MatePanelAppletFrameDBus > MatePanelAppletFrameDBus { background: none; }$'
    create: true

# ***

- name: One last kill mate-panel — Restart mate-panel so it renders correctly
  ansible.builtin.shell: killall -s 9 mate-panel
  ignore_errors: yes

# ***

# SAVVY/2024-02-16: In practice, mate-panel restarts itself, but if you've
# been fiddling around in the terminal yourself, it might not, in which
# case you can start it thusly::
#
#   mate-panel --replace &
#
# DUNNO: I tried (re)starting mate-panel from Ansible, but had no success, e.g.,
#
#   - name: Ensure mate-panel starts
#     # ansible.builtin.shell: mate-panel --replace &
#     # NO OUTPUT
#     #
#     ansible.builtin.shell: mate-panel --replace
#     # OUTPUT (stderr):
#     # (mate-panel:2815372): Gtk-WARNING **: 19:34:11.022: cannot open display:
#     #
#     # ansible.builtin.shell: startx mate-panel --replace
#     # HANGS
#     #
#
# - I also tried forwarding X11, but that didn't work (and it makes each Ansible
#   step run much slower), e.g.,
#
#     ANSIBLE_DEBUG=0 ANSIBLE_SSH_ARGS="-o ForwardX11=yes" \
#       ansible-playbook ~/.zoidy/site.yml -l ${managed_node} --tags zoidy_panelsweet
#     # Also:
#     ANSIBLE_DEBUG=0 ANSIBLE_SSH_ARGS='-C -o ForwardX11=yes -o ControlMaster=auto \
#         -o ControlPersist=60s -o KbdInteractiveAuthentication=no' \
#       ansible-playbook ~/.zoidy/site.yml -l ${managed_node} --tags zoidy_panelsweet
#
# - So if you don't see mate-panel restart, do it manually from a terminal:
#
#   mate-panel --replace &

# ***

# Finally, capture the new dconf settings.
# - KLUGE/2024-02-16: Beginning with latest Linux Mint 21.3 (after upgrading
#   my laptop from LM 19.3!), sometimes when I logon after locking my desktop,
#   the window-list panel and the launchers panel swap positions. The easiest
#   way to recover is to reload the dconf settings, which mate-panel reacts to
#   immediately. E.g.,
#
#     cat ~/.local/share/zoidy_panelsweet/dconf--org-mate-panel.dump \
#       | dconf load /org/mate/panel/

- name: Ensure MATE Panel dconf dump directory exists
  ansible.builtin.file:
    state: directory
    path: "{{ ansible_env.HOME }}/.local/share/zoidy_panelsweet/"

- name: Capture MATE Panel dconf dump (for mate-panel logon reset kludge)
  ansible.builtin.shell:
    dconf dump /org/mate/panel/ \
      > "{{ ansible_env.HOME }}/.local/share/zoidy_panelsweet/dconf--org-mate-panel.dump"

# Install service to restore mate-panel layout on unlock

- name: "Create the user systemd service unit to restore mate-panel layout"
  ansible.builtin.template:
    src: user/restore-mate-panels.service
    dest: "{{ ansible_env.HOME }}/.config/systemd/user"

- name: "Create the user systemd daemon script to restore mate-panel layout"
  ansible.builtin.template:
    src: user/restore-mate-panels.sh
    dest: "{{ ansible_env.HOME }}/.local/bin"
    mode: "0755"

# E.g.,
#   systemctl --user daemon-reload
#   systemctl --user enable --now restore-mate-panels.service
- name: "Start the user systemd timer"
  ansible.builtin.systemd_service:
    name: restore-mate-panels.service
    state: started
    enabled: true
    scope: user
    daemon_reload: true

# ***

# CPYST: Run this if mate-panel doesn't restart (as documented above):
#
#   mate-panel --replace &

